### ISSUE TITLE
eyed3 requirement

### ISSUE THREAD

**Issue by Saibot942** [engineervix/Bible-Playlist-Generator#2]
It looks like there is also a prerequisite to install the eyeD3 module.  I have tested with eyeD3-0.6.18 in Python2.7, but I was getting an error that the module doesn't exist:

> $ python ./scripture_playlist_gen.py 1
> Traceback (most recent call last):
>   File "./scripture_playlist_gen.py", line 24, in <module>
>     import eyed3
> ImportError: No module named eyed3

Eventually, I realized the module has an uppercase 'D' in the name, so I edited the python script to use that.  Now I'm getting an error about an invalid attribute:

> $ python ./scripture_playlist_gen.py 1
> The playlist for day 1 has been created successfully.
> Copying of the Bible Chapters into the day001 directory was successful.
> Traceback (most recent call last):
>   File "./scripture_playlist_gen.py", line 437, in <module>
>     audiofile = eyeD3.load(f)
> AttributeError: 'module' object has no attribute 'load'

Can you tell me what version of eyeD3 you tested with?

**Comment by engineervix** [comment]
Hi @Saibot942,

Thanks for pointing out this issue, [eyeD3](http://eyed3.nicfit.net/) is indeed a requirement! I don't know why I didn't add that in the [README](https://github.com/engineervix/Bible-Playlist-Generator/blob/master/README.md)! file! I'll edit it to include this requirement.
I have been running this script for a long time now using eyeD3 version 0.7.9, which you can install as follows:

`pip install https://github.com/nicfit/eyeD3/archive/v0.7.9.tar.gz`

For some weird reason, I've always installed eyeD3 that way. `pip install eyeD3` hasn't always worked for me!

Please let me know how it goes. I must mention that I use python2, I've not tested it in python3, but I think it should still work!

Grace and Peace.

**Comment by Saibot942** [comment]
Thanks, so much, Victor.  That resolved the issues with eyeD3.

I was using eyeD3-0.6.18 that I installed manually.  I had to use PIP to uninstall the old version then install v0.7.9, as you indicated.  No more failures with Python script execution.

Thanks again!

**Comment by engineervix** [comment]
@Saibot942 you're most welcome brother! I'm glad the issue has been resolved! Happy listening! 
😊
